"""Automation helpers for Playwright scripts and STL upload workflows."""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Sequence


@dataclass(frozen=True)
class PlaywrightScriptConfig:
    """Configuration describing how to automate an STL upload with Playwright."""

    url: str
    upload_path: Path
    upload_selector: str = "input[type=file]"
    start_selectors: Sequence[str] = ()
    extra_clicks: Sequence[str] = ()
    submit_selector: str | None = None
    wait_for_network_idle: bool = True
    wait_time_ms: int = 5000
    headless: bool = False
    notes: Sequence[str] = ()


def render_playwright_script(config: PlaywrightScriptConfig) -> str:
    """Return a ready-to-run Playwright automation script for STL uploads."""

    lines: list[str] = [
        "#!/usr/bin/env python3",
        '"""Automate STL uploads with Playwright (generated by Auto3D)."""',
    ]

    for note in config.notes:
        lines.append(f"# NOTE: {note}")
    if config.notes:
        lines.append("")

    lines.extend(
        [
            "from pathlib import Path",
            "",
            "from playwright.sync_api import sync_playwright",
            "",
            f'URL = "{config.url}"',
            f'UPLOAD_PATH = Path(r"{config.upload_path}")',
            f'UPLOAD_SELECTOR = "{config.upload_selector}"',
            "",
            "",
            "def run() -> None:",
            "    with sync_playwright() as playwright:",
            f"        browser = playwright.chromium.launch(headless={config.headless})",
            "        page = browser.new_page()",
            '        page.goto(URL, wait_until="domcontentloaded")',
        ]
    )

    for selector in config.start_selectors:
        lines.append(f'    page.click("{selector}")')

    lines.append('    page.set_input_files(UPLOAD_SELECTOR, str(UPLOAD_PATH))')

    for selector in config.extra_clicks:
        lines.append(f'    page.click("{selector}")')

    if config.submit_selector:
        lines.append(f'    page.click("{config.submit_selector}")')

    if config.wait_for_network_idle:
        lines.append('    page.wait_for_load_state("networkidle")')

    if config.wait_time_ms:
        lines.append(f'    page.wait_for_timeout({config.wait_time_ms})')

    lines.extend(
        [
            "    browser.close()",
            "",
            "",
            'if __name__ == "__main__":',
            "    run()",
            "",
        ]
    )

    return "\n".join(lines) + "\n"


def write_playwright_script(path: Path, config: PlaywrightScriptConfig) -> Path:
    """Write the rendered Playwright script to *path* and return the path."""

    path = path.expanduser().resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_playwright_script(config), encoding="utf-8")
    return path


def automation_guidelines() -> list[str]:
    """Return curated guidance for running the generated automation scripts."""

    return [
        "Install Playwright and its browsers once: `pip install playwright` then `playwright install`.",
        "Use non-headless mode while recording selectors so you can watch each interaction.",
        "Keep selectors specific (IDs or data-test attributes) to avoid brittle automations.",
        "Store environment secrets (logins, API keys) outside of scripts – use environment variables or Playwright's auth storage.",
        "Validate uploads on a staging environment before pointing automation at production storefronts.",
        "Schedule dry-run tests with `pytest` or the Auto3D test command so the automation stays healthy over time.",
    ]


__all__ = [
    "PlaywrightScriptConfig",
    "render_playwright_script",
    "write_playwright_script",
    "automation_guidelines",
]
